#pragma once

#include "rust/cxx.h"

namespace urglance {
    // Forward declaration of the shared struct generated by cxx
    struct PreviewData;

    // Main extraction entry point exposed to Rust via FFI
    PreviewData extract_file_preview(rust::Str file_path);
}
